/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import type { PriceType, PricingModel, ReferencePriceLanes } from '../types'
import {
  normalizeTierLabel,
  type ParsedTier,
  type TierCondition,
} from './billing-expr'
import {
  getDynamicPricingTiers,
  getTimeRateVariants,
  isDynamicPricingModel,
  timeRateVariantLabel,
  type TimeRateVariant,
} from './dynamic-price'
import { tokenPriceUSD } from './price'

type Translate = (key: string) => string

/** Reference lane each expression variable states, where they line up. */
export const TIER_FIELD_REFERENCE_LANES: Record<
  string,
  keyof ReferencePriceLanes
> = {
  inputPrice: 'input',
  outputPrice: 'output',
  cacheReadPrice: 'cached_input',
  cacheReadExplicitPrice: 'cache_hit',
  cacheCreatePrice: 'cache_creation',
  cacheCreate1hPrice: 'cache_creation_1h',
}

const REFERENCE_LANE_ORDER: (keyof ReferencePriceLanes)[] = [
  'input',
  'output',
  'cached_input',
  'cache_creation',
  'cache_creation_1h',
  'cache_hit',
]

/** Ratio-configured price each lane compares against, for non-tiered models. */
const STATIC_TYPE_REFERENCE_LANES: {
  staticType: PriceType
  lane: keyof ReferencePriceLanes
}[] = [
  { staticType: 'input', lane: 'input' },
  { staticType: 'output', lane: 'output' },
  { staticType: 'cache', lane: 'cached_input' },
  { staticType: 'create_cache', lane: 'cache_creation' },
]

/**
 * The reference lanes worth configuring for a model: those its own pricing
 * table renders as columns. Falls back to every lane when nothing maps (no
 * expression, or one priced purely on unmapped quantities such as audio).
 */
export function getReferenceLaneKeys(
  model: PricingModel
): (keyof ReferencePriceLanes)[] {
  const tiers = isDynamicPricingModel(model)
    ? getDynamicPricingTiers(model)
    : []
  const relevant = new Set<keyof ReferencePriceLanes>()
  if (tiers.length > 0) {
    for (const [field, lane] of Object.entries(TIER_FIELD_REFERENCE_LANES)) {
      const priced = tiers.some((tier) => {
        const value = Number(tier[field])
        return Number.isFinite(value) && value > 0
      })
      if (priced) relevant.add(lane)
    }
  } else {
    for (const { staticType, lane } of STATIC_TYPE_REFERENCE_LANES) {
      if (Number.isFinite(tokenPriceUSD(model, staticType, 1))) {
        relevant.add(lane)
      }
    }
  }
  if (relevant.size === 0) return [...REFERENCE_LANE_ORDER]
  return REFERENCE_LANE_ORDER.filter((lane) => relevant.has(lane))
}

/**
 * One rate condition a model prices under: a parsed expression tier crossed
 * with a time-rate variant. The details drawer renders one gateway price row
 * per condition, and per-condition reference prices are stored under `key`.
 */
export type RateCondition = {
  /**
   * Storage key for this condition's reference price ('' for the generic
   * unconditioned row, which maps to the default reference price). Derived,
   * never typed by an admin; must be stable across renders and between the
   * drawer and the settings card, which is why it lives here.
   */
  key: string
  /** Display string, identical in the drawer and the settings matrix. */
  label: string
  /**
   * The tier's own name, when the expression carries one and the label above
   * already states the condition it stands for. Rendered as a second line.
   */
  detail?: string
  tier: ParsedTier
  variant: TimeRateVariant | null
}

/** Autogenerated tier labels that mean "no real condition"; display as Standard. */
export const GENERIC_TIER_LABELS = new Set(['base', 'default'])

/** What the visual tier editor names a tier the admin left unnamed. */
const GENERATED_TIER_LABEL = /^tier[_-]?\d+$/

/** The quantities a tier branches on, named the way the pricing table reads. */
const CONDITION_VAR_LABELS: Record<TierCondition['var'], string> = {
  len: 'Input length',
  p: 'Input tokens',
  c: 'Output tokens',
}

const TOKEN_COUNT_FORMAT = new Intl.NumberFormat('en-US', {
  maximumFractionDigits: 1,
  useGrouping: false,
})

/** A token threshold the way the pricing pages state it: 128000 → "128K". */
export function formatTokenCount(value: number): string {
  const count = Number(value)
  if (!Number.isFinite(count)) return ''
  if (Math.abs(count) >= 1_000_000) {
    return `${TOKEN_COUNT_FORMAT.format(count / 1_000_000)}M`
  }
  if (Math.abs(count) >= 1_000) {
    return `${TOKEN_COUNT_FORMAT.format(count / 1_000)}K`
  }
  return TOKEN_COUNT_FORMAT.format(count)
}

/**
 * The span of one condition variable a tier bills on. `min`/`max` are
 * ±Infinity on an unbounded side.
 */
export type TierRange = {
  variable: TierCondition['var']
  min: number
  minInclusive: boolean
  max: number
  maxInclusive: boolean
}

/**
 * The range each tier actually bills on. A billing expression is an ordered
 * if/else chain, so a tier bills on its own condition minus everything an
 * earlier tier already claimed — which is the only way the trailing `else`
 * tier, written with no condition at all, can state a range.
 *
 * A tier yields null when its range is not a single span: conditions on mixed
 * variables, or a chain that leaves a hole behind. Those keep their labels.
 */
export function tierBillingRanges(tiers: ParsedTier[]): (TierRange | null)[] {
  const variables = new Set(
    tiers.flatMap((tier) => tier.conditions.map((condition) => condition.var))
  )
  if (variables.size !== 1) return tiers.map(() => null)
  const variable = [...variables][0]

  let remaining: TierRange | null = {
    variable,
    min: Number.NEGATIVE_INFINITY,
    minInclusive: false,
    max: Number.POSITIVE_INFINITY,
    maxInclusive: false,
  }
  return tiers.map((tier) => {
    if (!remaining) return null
    const claimed = remaining
    // What this tier bills on: the unclaimed span narrowed by its conditions.
    const range: TierRange = { ...claimed }
    for (const { op, value } of tier.conditions) {
      const inclusive = op === '<=' || op === '>='
      if (op === '<' || op === '<=') {
        if (value < range.max || (value === range.max && !inclusive)) {
          range.max = value
          range.maxInclusive = inclusive
        }
      } else if (value > range.min || (value === range.min && !inclusive)) {
        range.min = value
        range.minInclusive = inclusive
      }
    }

    // A tier the chain above it already shadowed never fires, and claims
    // nothing from the tiers below it.
    if (
      range.min > range.max ||
      (range.min === range.max && !(range.minInclusive && range.maxInclusive))
    ) {
      return null
    }

    const lowerAligned =
      range.min === claimed.min && range.minInclusive === claimed.minInclusive
    const upperAligned =
      range.max === claimed.max && range.maxInclusive === claimed.maxInclusive
    if (lowerAligned && !upperAligned) {
      remaining = {
        variable,
        min: range.max,
        minInclusive: !range.maxInclusive,
        max: claimed.max,
        maxInclusive: claimed.maxInclusive,
      }
    } else if (upperAligned && !lowerAligned) {
      remaining = {
        variable,
        min: claimed.min,
        minInclusive: claimed.minInclusive,
        max: range.min,
        maxInclusive: !range.minInclusive,
      }
    } else {
      remaining = null
    }
    return range
  })
}

/** "Input length ≤ 128K" — the condition a rate row bills under. */
export function formatTierRange(range: TierRange, t: Translate): string {
  const variable = t(CONDITION_VAR_LABELS[range.variable])
  const hasMin = Number.isFinite(range.min)
  const hasMax = Number.isFinite(range.max)
  if (!hasMin && !hasMax) return ''
  if (hasMin && hasMax) {
    return `${variable} ${formatTokenCount(range.min)}–${formatTokenCount(range.max)}`
  }
  if (hasMax) {
    return `${variable} ${range.maxInclusive ? '≤' : '<'} ${formatTokenCount(range.max)}`
  }
  return `${variable} ${range.minInclusive ? '≥' : '>'} ${formatTokenCount(range.min)}`
}

/** The single rate condition a model without a tiered expression bills on. */
export const STANDARD_RATE_CONDITION: ParsedTier = { label: '', conditions: [] }

/**
 * The variant half of a condition key. The variant's only stable identity is
 * its multiplier, but the labelKey slug reads better in hand-edited JSON and
 * only needs the multiplier suffix when several same-side multipliers exist
 * (the same rule timeRateVariantLabel uses for display).
 */
function timeVariantSlug(variant: TimeRateVariant): string {
  let base = 'standard'
  if (variant.labelKey === 'Peak Hours') base = 'peak'
  else if (variant.labelKey === 'Off-Peak Hours') base = 'offpeak'
  return variant.showMultiplier ? `${base}-x${variant.multiplier}` : base
}

export function rateConditionKey(
  tier: ParsedTier,
  variant: TimeRateVariant | null
): string {
  const raw = (tier.label || '').trim()
  const tierPart =
    !raw || GENERIC_TIER_LABELS.has(raw.toLowerCase())
      ? ''
      : // Tier labels are free prose from the billing expression; '/' keeps a
        // literal '|' from colliding with the key separator below.
        normalizeTierLabel(raw).replaceAll('|', '/')
  const variantPart = variant ? timeVariantSlug(variant) : ''
  if (tierPart && variantPart) return `${tierPart}|${variantPart}`
  return tierPart || variantPart
}

/**
 * Every rate condition the model's billing expression defines, in the order
 * the pricing table renders them. A model without a tiered expression yields
 * the single generic condition (key ''), which reference pricing resolves to
 * the default price.
 */
export function getRateConditions(
  model: PricingModel,
  t: Translate
): RateCondition[] {
  const tiers = isDynamicPricingModel(model)
    ? getDynamicPricingTiers(model)
    : []
  const timeVariants = getTimeRateVariants(model)
  const baseTiers = tiers.length > 0 ? tiers : [STANDARD_RATE_CONDITION]
  // The condition a tier bills under states more than its name does, so it
  // leads; a name the admin actually wrote follows it on a second line.
  const ranges = tierBillingRanges(baseTiers)
  const rows: {
    tier: ParsedTier
    range: TierRange | null
    variant: TimeRateVariant | null
  }[] =
    timeVariants.length > 0
      ? baseTiers.flatMap((tier, index) =>
          timeVariants.map((variant) => ({
            tier,
            range: ranges[index],
            variant,
          }))
        )
      : baseTiers.map((tier, index) => ({
          tier,
          range: ranges[index],
          variant: null,
        }))

  return rows.map(({ tier, range, variant }) => {
    const raw = (tier.label || '').trim()
    const normalized = raw.toLowerCase()
    const name =
      raw &&
      !GENERIC_TIER_LABELS.has(normalized) &&
      !GENERATED_TIER_LABEL.test(normalized)
        ? raw
        : ''
    const rangeLabel = range ? formatTierRange(range, t) : ''
    const tierLabel = rangeLabel || name || t('Standard')
    let label = tierLabel
    if (variant) {
      const variantLabel = timeRateVariantLabel(variant, t)
      label =
        baseTiers.length > 1 ? `${tierLabel} · ${variantLabel}` : variantLabel
    }
    return {
      key: rateConditionKey(tier, variant),
      label,
      detail: rangeLabel && name ? name : undefined,
      tier,
      variant,
    }
  })
}
