/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import type { PriceType, PricingModel, ReferencePriceLanes } from '../types'
import { normalizeTierLabel, type ParsedTier } from './billing-expr'
import {
  getDynamicPricingTiers,
  getTimeRateVariants,
  isDynamicPricingModel,
  timeRateVariantLabel,
  type TimeRateVariant,
} from './dynamic-price'
import { tokenPriceUSD } from './price'

type Translate = (key: string) => string

/** Reference lane each expression variable states, where they line up. */
export const TIER_FIELD_REFERENCE_LANES: Record<
  string,
  keyof ReferencePriceLanes
> = {
  inputPrice: 'input',
  outputPrice: 'output',
  cacheReadPrice: 'cached_input',
  cacheReadExplicitPrice: 'cache_hit',
  cacheCreatePrice: 'cache_creation',
}

const REFERENCE_LANE_ORDER: (keyof ReferencePriceLanes)[] = [
  'input',
  'output',
  'cached_input',
  'cache_creation',
  'cache_hit',
]

/** Ratio-configured price each lane compares against, for non-tiered models. */
const STATIC_TYPE_REFERENCE_LANES: {
  staticType: PriceType
  lane: keyof ReferencePriceLanes
}[] = [
  { staticType: 'input', lane: 'input' },
  { staticType: 'output', lane: 'output' },
  { staticType: 'cache', lane: 'cached_input' },
  { staticType: 'create_cache', lane: 'cache_creation' },
]

/**
 * The reference lanes worth configuring for a model: those its own pricing
 * table renders as columns. Falls back to every lane when nothing maps (no
 * expression, or one priced purely on unmapped quantities such as audio).
 */
export function getReferenceLaneKeys(
  model: PricingModel
): (keyof ReferencePriceLanes)[] {
  const tiers = isDynamicPricingModel(model)
    ? getDynamicPricingTiers(model)
    : []
  const relevant = new Set<keyof ReferencePriceLanes>()
  if (tiers.length > 0) {
    for (const [field, lane] of Object.entries(TIER_FIELD_REFERENCE_LANES)) {
      const priced = tiers.some((tier) => {
        const value = Number(tier[field])
        return Number.isFinite(value) && value > 0
      })
      if (priced) relevant.add(lane)
    }
  } else {
    for (const { staticType, lane } of STATIC_TYPE_REFERENCE_LANES) {
      if (Number.isFinite(tokenPriceUSD(model, staticType, 1))) {
        relevant.add(lane)
      }
    }
  }
  if (relevant.size === 0) return [...REFERENCE_LANE_ORDER]
  return REFERENCE_LANE_ORDER.filter((lane) => relevant.has(lane))
}

/**
 * One rate condition a model prices under: a parsed expression tier crossed
 * with a time-rate variant. The details drawer renders one gateway price row
 * per condition, and per-condition reference prices are stored under `key`.
 */
export type RateCondition = {
  /**
   * Storage key for this condition's reference price ('' for the generic
   * unconditioned row, which maps to the default reference price). Derived,
   * never typed by an admin; must be stable across renders and between the
   * drawer and the settings card, which is why it lives here.
   */
  key: string
  /** Display string, identical in the drawer and the settings matrix. */
  label: string
  tier: ParsedTier
  variant: TimeRateVariant | null
}

/** Autogenerated tier labels that mean "no real condition"; display as Standard. */
export const GENERIC_TIER_LABELS = new Set(['base', 'default'])

/** The single rate condition a model without a tiered expression bills on. */
export const STANDARD_RATE_CONDITION: ParsedTier = { label: '', conditions: [] }

/**
 * The variant half of a condition key. The variant's only stable identity is
 * its multiplier, but the labelKey slug reads better in hand-edited JSON and
 * only needs the multiplier suffix when several same-side multipliers exist
 * (the same rule timeRateVariantLabel uses for display).
 */
function timeVariantSlug(variant: TimeRateVariant): string {
  let base = 'standard'
  if (variant.labelKey === 'Peak Hours') base = 'peak'
  else if (variant.labelKey === 'Off-Peak Hours') base = 'offpeak'
  return variant.showMultiplier ? `${base}-x${variant.multiplier}` : base
}

export function rateConditionKey(
  tier: ParsedTier,
  variant: TimeRateVariant | null
): string {
  const raw = (tier.label || '').trim()
  const tierPart =
    !raw || GENERIC_TIER_LABELS.has(raw.toLowerCase())
      ? ''
      : // Tier labels are free prose from the billing expression; '/' keeps a
        // literal '|' from colliding with the key separator below.
        normalizeTierLabel(raw).replaceAll('|', '/')
  const variantPart = variant ? timeVariantSlug(variant) : ''
  if (tierPart && variantPart) return `${tierPart}|${variantPart}`
  return tierPart || variantPart
}

/**
 * Every rate condition the model's billing expression defines, in the order
 * the pricing table renders them. A model without a tiered expression yields
 * the single generic condition (key ''), which reference pricing resolves to
 * the default price.
 */
export function getRateConditions(
  model: PricingModel,
  t: Translate
): RateCondition[] {
  const tiers = isDynamicPricingModel(model)
    ? getDynamicPricingTiers(model)
    : []
  const timeVariants = getTimeRateVariants(model)
  const baseTiers = tiers.length > 0 ? tiers : [STANDARD_RATE_CONDITION]
  const rows: { tier: ParsedTier; variant: TimeRateVariant | null }[] =
    timeVariants.length > 0
      ? baseTiers.flatMap((tier) =>
          timeVariants.map((variant) => ({ tier, variant }))
        )
      : baseTiers.map((tier) => ({ tier, variant: null }))

  return rows.map(({ tier, variant }) => {
    const raw = (tier.label || '').trim()
    const tierLabel =
      raw && !GENERIC_TIER_LABELS.has(raw.toLowerCase()) ? raw : t('Standard')
    let label = tierLabel
    if (variant) {
      const variantLabel = timeRateVariantLabel(variant, t)
      label =
        baseTiers.length > 1 ? `${tierLabel} · ${variantLabel}` : variantLabel
    }
    return { key: rateConditionKey(tier, variant), label, tier, variant }
  })
}
